name: Deploy Github pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK '9.0.x'
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'
      - name: Update base url
        run: sed -i 's|<base href="/" />|\<base href="/YachtLogHoursCalculator/" /\>|g' ./YachtLogHoursCalculator/wwwroot/index.html
      - name: Build
        run: dotnet build --configuration Release
      - name: Publish
        run: dotnet publish ./YachtLogHoursCalculator/YachtLogHoursCalculator.csproj -c Release -o output
      - name: Add .nojekyll file
        run: touch output/wwwroot/.nojekyll
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: output/wwwroot